name: Java CI

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Set up JDK 17
        uses: actions/setup-java@v2
        with:
          java-version: '17'
          distribution: 'adopt'
          cache: maven

      - name: Set up environment variables
        run: |
          echo "MYSQLDB_USER=${{ secrets.MYSQLDB_USER }}" >> $GITHUB_ENV
          echo "MYSQLDB_ROOT_PASSWORD=${{ secrets.MYSQLDB_ROOT_PASSWORD }}" >> $GITHUB_ENV
          echo "MYSQLDB_DATABASE=${{ secrets.MYSQLDB_DATABASE }}" >> $GITHUB_ENV
          echo "MYSQLDB_LOCAL_PORT=${{ secrets.MYSQLDB_LOCAL_PORT }}" >> $GITHUB_ENV
          echo "MYSQLDB_DOCKER_PORT=${{ secrets.MYSQLDB_DOCKER_PORT }}" >> $GITHUB_ENV
          echo "SPRING_LOCAL_PORT=${{ secrets.SPRING_LOCAL_PORT }}" >> $GITHUB_ENV
          echo "SPRING_DOCKER_PORT=${{ secrets.SPRING_DOCKER_PORT }}" >> $GITHUB_ENV
          echo "DEBUG_PORT=${{ secrets.DEBUG_PORT }}" >> $GITHUB_ENV
          echo "JWT_EXPIRATION=${{ secrets.JWT_EXPIRATION }}" >> $GITHUB_ENV
          echo "JWT_SECRET=${{ secrets.JWT_SECRET }}" >> $GITHUB_ENV
          echo "DROPBOX_ACCESS_TOKEN=${{ secrets.DROPBOX_ACCESS_TOKEN }}" >> $GITHUB_ENV
          echo "SPRING_MAIL_PORT=${{ secrets.SPRING_MAIL_PORT }}" >> $GITHUB_ENV
          echo "SPRING_MAIL_USERNAME=${{ secrets.SPRING_MAIL_USERNAME }}" >> $GITHUB_ENV
          echo "SPRING_MAIL_PASSWORD=${{ secrets.SPRING_MAIL_PASSWORD }}" >> $GITHUB_ENV

      - name: Build with Maven
        run: mvn --batch-mode --update-snapshots verify
